### ISSUE TITLE
How to install LibreOffice extension?

### ISSUE THREAD

**Issue by davidak** [gkarsay/parlatype#92]
The documentation says:

> the recognized speech will be printed in LibreOffice, if the Parlatype Extension is installed.

https://www.parlatype.org/help-online/asr.html

but there are no instructions how to install it

I searched the extensions, but there is none

https://extensions.libreoffice.org/?q=Parlatype&action_doExtensionSearch=Search

Please add a documentation where to find it and how to install it.

**Comment by gkarsay** [comment]
Thanks for the hint, I know it's not well documented. As a quick response:
It's available as a package in Arch LInux (AUR), Debian 11 and Ubuntu 21.04 (package name: libreoffice-parlatype)

Releases are here: https://github.com/gkarsay/parlatype-libreoffice-extension/releases
Download the file named Parlatype.oxt. It works with the corresponding version of Parlatype.
In LibreOffice in the menu bar: Tools --> Extension Manager --> Add

I will close this when it's properly documented.

**Comment by davidak** [comment]
I was not able to install it, but that might be related to my distro. NixOS is a bit special.

![Screenshot from 2021-12-10 22-13-31](https://user-images.githubusercontent.com/91113/145642102-de95d766-122f-4b0a-862a-ce070703bc96.png)

I will check if LibreOffice extensions have to be packaged or something.

**Comment by davidak** [comment]
>First you have to know which python interpreter is used by LibreOffice.

The `python3` package is specified as dependency, which is Python 3.9.6, but no other python packages.

https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/office/libreoffice/default.nix#L399

>A way to find out is installing the APSO extension

```
APSO python console [LibreOffice]
3.9.6 (default, Jun 28 2021, 08:57:49) 
[GCC 10.3.0]
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
''
>>> import dbus
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/nix/store/1pizyhy66y8jyyz71paf93fcwcd9k3n9-libreoffice-7.1.7.2/lib/libreoffice/program/uno.py", line 345, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
ModuleNotFoundError: No module named 'dbus'
>>> import gi
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/nix/store/1pizyhy66y8jyyz71paf93fcwcd9k3n9-libreoffice-7.1.7.2/lib/libreoffice/program/uno.py", line 345, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
ModuleNotFoundError: No module named 'gi'
>>> 
```
It might be possible that no one tried to use extensions before. I will talk to the maintainers.

**Comment by gkarsay** [comment]
Interesting, I get:
```
APSO python console [LibreOffice]
3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
'/usr/bin/python3'
```
> It might be possible that no one tried to use extensions before. I will talk to the maintainers.

APSO is an extension, obviously working.
